---
# This role will install MySQL and create db user and give permissions.

- name: Installing Mysql package
  yum: 
    name: {{ item }}
    state: present
  with_items:
    - mysql-server
    - MySQL-python

- name: Configuring SELinux to start mysql on any port
  seboolean: 
    name: mysql_connect_any
    state: true 
    persistent: yes
  when: sestatus.rc != 0

- name: Creating Mysql configuration file
  template: 
    src: my.cnf.j2
    dest: /etc/my.cnf
  notify:
  - restart mysql

- name: Starting Mysql Service
  service: 
    name: mysqld
    state: started
    enabled: yes

- name: Creating Application Database
  mysql_db:
    name: {{ dbname }}
    state: present

- name: Creating Application DB User
  mysql_user: 
    name: {{ dbuser }}
    password: {{ upassword }}
    priv: *.*:ALL
    host: '%'
    state: present